### ISSUE TITLE
module 'pygfunction.utilities' has no attribute 'segment_ratios'

### ISSUE THREAD

**Issue by DavideDC9** [j-c-cook/ghedt#96]
Traceback (most recent call last):
  File "..................................................................................................../ghedt/examples/Design/find_bi_zoned_rectangle.py", line 230, in <module>
    main()
  File "..................................................................................................../ghedt/examples/Design/find_bi_zoned_rectangle.py", line 151, in main
    bisection_search = design_single_u_tube.find_design(disp=True)
  File "....................................................................................................\ghedt\design.py", line 85, in find_design
    bisection_search = dt.search_routines.BisectionZD(
  File "....................................................................................................\ghedt\search_routines.py", line 261, in __init__
    Bisection1D.__init__(
  File "....................................................................................................\ghedt\search_routines.py", line 44, in __init__
    g_function = dt.gfunction.compute_live_g_function(
  File "....................................................................................................\ghedt\gfunction.py", line 92, in compute_live_g_function
    gfunc = calculate_g_function(
  File "....................................................................................................\ghedt\gfunction.py", line 44, in calculate_g_function
    segment_ratios = gt.utilities.segment_ratios(
AttributeError: module 'pygfunction.utilities' has no attribute 'segment_ratios'

**Comment by j-c-cook** [comment]
Can you type `pip list` and let me know which version of `pygfunction` you are running? We introduced `segment_ratios` in version 2.1 (https://github.com/MassimoCimmino/pygfunction/blob/master/CHANGELOG.md#version-210-2021-11-12). 

You can run `pip install -r requirements.txt` to install all the required modules. It should update your `pygfunction` installation if you are running older than 2.1.

**Comment by DavideDC9** [comment]
not solved by updating, here the pip list:

Package         Version
--------------- --------
CoolProp        6.4.1
cycler          0.11.0
et-xmlfile      1.1.0
fonttools       4.29.0
kiwisolver      1.3.2
matplotlib      3.5.1
numpy           1.22.1
opencv-python   4.5.4.58
openpyxl        3.0.9
packaging       21.3
pandas          1.4.0
Pillow          9.0.0
pip             21.1.2
pygfunction     2.1.0
pyparsing       3.0.7
python-dateutil 2.8.2
pytz            2021.3
scipy           1.7.3
setuptools      57.0.0
six             1.16.0
wheel           0.36.2

**Comment by j-c-cook** [comment]
What IDE are you using? Is it accessing the same environment that you list there?

**Comment by DavideDC9** [comment]
I m using pycharm, and yes I have double checked, all the packages and correct versions are installed

**Comment by j-c-cook** [comment]
Could you go to `Settings` -> `Project: ghedt` -> `Python Interpretor` and share a screen shot of your interpreter where I can see that its `pygfunction 2.1.0`. 

![image](https://user-images.githubusercontent.com/39248734/151203274-061e4768-5071-4393-98b6-095b83a0a7dd.png)

**Comment by DavideDC9** [comment]
![image](https://user-images.githubusercontent.com/84395463/151203497-e0d1be8c-26d3-4421-a1d1-ca6e331de249.png)

**Comment by j-c-cook** [comment]
That is strange. If you tag @MassimoCimmino's version `2.1.0` release, you can see that a `pygfunction.utilities.segment_ratios()` function does exist. 
![image](https://user-images.githubusercontent.com/39248734/151203880-c9b9f2c9-c9f8-4f25-a40a-3d3fcd949015.png)

Have you looked at the pygfunction `utilitites.py` file in your environment to see if it has the `segment_ratios()` function. Perhaps try 
```
pip uninstall pygfunction
pip install pygfunction==2.1.0
```

@mitchute have you ran into this issue?

**Comment by DavideDC9** [comment]
![image](https://user-images.githubusercontent.com/84395463/151206988-a7f837ce-5245-47ad-83ff-16cb8957a1e3.png)

**Comment by DavideDC9** [comment]
Yes, I even tried to define it on the example itself

**Comment by j-c-cook** [comment]
If you look in `C:\Users\davide\PychardProjects\pygfunction\G\venv_2` and find the `pygfunction` package, is the `segment_ratios` function inside of `utilitites.py`?

**Comment by j-c-cook** [comment]
On my system `pygfunction` is located in `lib/python3.7/site-packages/pygfunction`. 
![image](https://user-images.githubusercontent.com/39248734/151208101-bb0a5f50-37f1-4484-8d48-3c46bb436c1e.png)

From there, when I open up `utilities.py` I can see that the `segment_ratios` function is defined. Is it in yours?
![image](https://user-images.githubusercontent.com/39248734/151208296-2c3d0645-c07b-4182-81b5-dbcaebefe65e.png)

**Comment by j-c-cook** [comment]
That is bizarre. Is the example file in `ghedt` running now?

**Comment by j-c-cook** [comment]
Is that a `ghedt` or `pygfunction` issue?

**Comment by j-c-cook** [comment]
I think you need to replace all of the `pygfunction` files in that directory with version `2.1` files.

**Comment by MassimoCimmino** [comment]
> It has changed. I get this error message: AssertionError: Method 'MIFT' is not an acceptable method. Please provide one of the following inputs : ['detailed', 'similarities']

This is a `pygfunction` v2.0 error. There was a mistake in the reporting which got fixed in v2.1 (and `'equivalent'` was also introduced). My guess is `ghedt` is trying to use the missing `'equivalent'` solver.

**Comment by j-c-cook** [comment]
Yes, the example he is running is trying to use the default g-function calculation (`equivalent` with unequal segment lengths). Both introduced in `pygfunction` version 2.1. 

@DavideDC9 The issue appears to be that your package manager is reporting that you have `pygfunction==2.1` installed when the code contained in the package is actually `pygfunction==2.0`. 

I'm going to close this issue because we have resolved what the original error was, and have found that the solution (for now) is for @DavideDC9 to replace his `pygfunction` installation with files from the [v2.1.0](https://github.com/MassimoCimmino/pygfunction/releases/tag/v2.1.0) release. The heart of the issue is located outside of `ghedt`, perhaps in `venv`.
